apiVersion: v1
kind: ServiceAccount
metadata:
  name: workload-sa
  namespace: default
  annotations:
    azure.workload.identity/client-id: "b3bcbb1d-0eeb-4195-81a1-0cff13ec7cae"
  labels:
    azure.workload.identity/use: "true"
